graph TD
  top(("top"))
  c0["***0<br/>spread | flags.aon:32:14"]
  c1["**5<br/>pref | layers.aon:20:46"]
  c2["*25<br/>pref | layers.aon:27:29"]
  val{{"*25"}}
  top --> c0
  c0 --> c1
  c1 --> c2
  c2 --> val
