#!/usr/bin/env bash
# check.sh --- code generation, as far as the language goes today.
#
# One model, three targets, each over a different slice of it. Every
# line of every generated file is computed by the unifier; the only
# step this case does outside Aontu is the FOLD that turns a list of
# lines into a file, because the language has no fold over strings.
# That boundary is asserted here rather than described: the SQL golden
# is REFUSED by a real SQL parser, for the one reason a fold would fix.
#
# Runnable from any cwd. `go` is optional -- the checks that need it
# skip with a note.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$DIR/../.."
AONTU="${AONTU:-node $REPO/ts/bin/aontu.js}"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

pass=0
fail() { echo "FAIL: $1" >&2; exit 1; }
ok() { pass=$((pass + 1)); echo "ok $pass - $1"; }
skip() { pass=$((pass + 1)); echo "ok $pass - $1 # SKIP"; }

# The fold the language cannot do: head, then the body lines, then
# tail, one blank line between units. Six lines of Python standing in
# for `join`, which is G9 phase 2.
fold() {
  python3 -c '
import json, sys
for u in json.load(sys.stdin):
    print(u["head"])
    for line in u["body"]:
        print(line)
    print(u["tail"])
    print()
'
}

emit() { # emit <transform> <banner-comment-marker> [extra-header-line...]
  local xf="$1" mark="$2"; shift 2
  {
    echo "$mark Code generated by aontu from model.aon. DO NOT EDIT."
    echo
    for extra in "$@"; do echo "$extra"; echo; done
    $AONTU get '$.units' --include-root "$DIR" "$DIR/$xf" | fold
  }
}

# ----------------------------------------------------------------
# 1. Each transform stands up and yields the unit shape the fold
# consumes: head, a list body, tail. Nothing here is a string the
# generator was handed -- every line was computed from the model.
for xf in gen-go gen-ts gen-sql; do
  $AONTU get '$.units' --include-root "$DIR" "$DIR/$xf.aon" > "$WORK/$xf.json" \
    || fail "$xf: transform did not evaluate"
  python3 - "$WORK/$xf.json" <<'EOF'
import json, sys
units = json.load(open(sys.argv[1]))
assert 2 == len(units), len(units)
for u in units:
    assert isinstance(u["head"], str) and u["head"]
    assert isinstance(u["body"], list) and 3 == len(u["body"])
    assert all(isinstance(l, str) for l in u["body"])
    assert isinstance(u["tail"], str)
EOF
  [ $? -eq 0 ] || fail "$xf: unit shape wrong"
done
ok "three transforms evaluate to two units each, three body lines apiece"

# 2. The generated files are byte-identical to the goldens. This is
# the real assertion: the bytes below were produced by the unifier.
emit gen-go.aon '//' 'package acme' > "$WORK/types.go"
emit gen-ts.aon '//'                 > "$WORK/types.ts"
emit gen-sql.aon '--'                > "$WORK/schema.sql"
for f in types.go types.ts schema.sql; do
  diff -u "$DIR/expected/$f" "$WORK/$f" \
    || fail "$f drifted from expected/$f"
done
ok "three generated files match their goldens byte for byte"

# 3. The Go output is REAL Go: it compiles. A generator whose output
# merely looks right is a generator nobody trusts.
if command -v go >/dev/null 2>&1; then
  mkdir -p "$WORK/gomod" && cp "$WORK/types.go" "$WORK/gomod/"
  printf 'module gencheck\n\ngo 1.24\n' > "$WORK/gomod/go.mod"
  (cd "$WORK/gomod" && go build ./...) \
    || fail "the generated Go does not compile"
  ok "the generated Go compiles"

  # 4. ...and gofmt WOULD change it, by aligning the struct tags. That
  # is the formatter hand-off, pinned: the generator's job is correct
  # code, the formatter's job is idiomatic layout. If this ever stops
  # being true the generator has started doing layout, which is the
  # design decision to revisit, not a test to update quietly.
  [ -n "$(cd "$WORK/gomod" && gofmt -l .)" ] \
    || fail "gofmt no longer reformats the output -- see check.sh note 4"
  ok "gofmt realigns the output: layout is the formatter's job, not ours"
else
  skip "the generated Go compiles (no go toolchain)"
  skip "gofmt realigns the output (no go toolchain)"
fi

# 5. THE ONE MISSING PRIMITIVE, asserted rather than described. Every
# column line ends in a comma because a spread can only put a
# separator AFTER each element; putting one BETWEEN N elements is a
# fold, and the language has none over strings. So the SQL does not
# parse -- and this check proves it with a real parser instead of
# taking the README's word for it. `join(bag, sep)` is G9 phase 2.
python3 - "$WORK/schema.sql" <<'EOF'
import sqlite3, sys
sql = open(sys.argv[1]).read()
assert sql.count(",\n);") == 2, "expected the trailing comma on both tables"
try:
    sqlite3.connect(":memory:").executescript(sql)
except sqlite3.OperationalError as e:
    assert "syntax error" in str(e), e
    sys.exit(0)
raise SystemExit("the SQL parsed -- the trailing-comma gap is gone; "
                 "if join() landed, rewrite gen-sql.aon and this check")
EOF
ok "the SQL is refused by a real parser: the missing fold, proven"

# 6. THE SLICES ARE REAL. Change only the `go` names in the model and
# the Go output must move while the TypeScript output must not -- the
# D5 claim that each target reads part of the model, checked rather
# than asserted.
sed 's/"Email"/"EmailAddr"/' "$DIR/model.aon" > "$WORK/model.aon"
cp "$DIR/gen-go.aon" "$DIR/gen-ts.aon" "$WORK/"
$AONTU get '$.units' --include-root "$WORK" "$WORK/gen-go.aon" | fold > "$WORK/go2.txt"
$AONTU get '$.units' --include-root "$WORK" "$WORK/gen-ts.aon" | fold > "$WORK/ts2.txt"
$AONTU get '$.units' --include-root "$DIR" "$DIR/gen-ts.aon" | fold > "$WORK/ts1.txt"
grep -q 'EmailAddr' "$WORK/go2.txt" \
  || fail "the go slice did not reach the Go output"
diff -q "$WORK/ts1.txt" "$WORK/ts2.txt" >/dev/null \
  || fail "a change to the go slice moved the TypeScript output"
ok "slices hold: the go rename moves Go and leaves TypeScript alone"

# 7. Generation is deterministic: the same model twice, the same bytes.
$AONTU get '$.units' --include-root "$DIR" "$DIR/gen-go.aon" | fold > "$WORK/again.txt"
$AONTU get '$.units' --include-root "$DIR" "$DIR/gen-go.aon" | fold > "$WORK/again2.txt"
diff -q "$WORK/again.txt" "$WORK/again2.txt" >/dev/null \
  || fail "two runs of the same transform differ"
ok "two runs of the same transform are byte-identical"

# 8. ADR-001: the Go port emits the same bytes. This is the check that
# matters most for a generator -- one model must not become two
# different files depending on which engine ran.
if command -v go >/dev/null 2>&1; then
  GOBIN="$WORK/aontu-go"
  (cd "$REPO/go" && go build -o "$GOBIN" ./cmd/aontu) \
    || fail "could not build the Go CLI"
  for xf in gen-go gen-ts gen-sql; do
    "$GOBIN" get '$.units' --include-root "$DIR" "$DIR/$xf.aon" | fold \
      > "$WORK/$xf.go.txt"
    $AONTU get '$.units' --include-root "$DIR" "$DIR/$xf.aon" | fold \
      > "$WORK/$xf.ts.txt"
    diff -u "$WORK/$xf.ts.txt" "$WORK/$xf.go.txt" \
      || fail "$xf: the two ports emit different bytes (ADR-001)"
  done
  ok "both ports emit byte-identical output for all three targets"
else
  skip "both ports emit byte-identical output (no go toolchain)"
fi

echo "all $pass checks passed"
