#!/usr/bin/env bash
# check.sh --- code generation, now that the language can finish the job.
#
# One model, three targets, each over a different slice of it. Until
# G9 phase 2 every LINE was computed by the unifier and the FILE was
# assembled by six lines of Python here, because putting a separator
# between N items is a fold and the language had none. `join` landed,
# and the fold is gone: each transform's `$.file` IS the artifact, and
# this script writes bytes.
#
# The check that used to prove the gap now proves it closed. The SQL
# golden was REFUSED by a real parser for the trailing comma a fold
# would fix; it is handed to the same parser and must PARSE.
#
# Runnable from any cwd. `go` is optional -- the checks that need it
# skip with a note.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$DIR/../.."
AONTU="${AONTU:-node $REPO/ts/bin/aontu.js}"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

pass=0
fail() { echo "FAIL: $1" >&2; exit 1; }
ok() { pass=$((pass + 1)); echo "ok $pass - $1"; }
skip() { pass=$((pass + 1)); echo "ok $pass - $1 # SKIP"; }

# The only host-side step left, and it is not assembly: `get` answers
# with a JSON string, so this unwraps it to the bytes it denotes.
# Nothing here decides layout, ordering or separators -- the transform
# already did.
unwrap() { python3 -c 'import json,sys; sys.stdout.write(json.load(sys.stdin))'; }

emit() { # emit <transform> <banner-comment-marker> [extra-header-line...]
  local xf="$1" mark="$2"; shift 2
  {
    echo "$mark Code generated by aontu from model.aon. DO NOT EDIT."
    echo
    for extra in "$@"; do echo "$extra"; echo; done
    $AONTU get '$.file' --include-root "$DIR" "$DIR/$xf" | unwrap
  }
}

# ----------------------------------------------------------------
# 1. Each transform yields ONE STRING that is the whole artifact --
# the shape the fold used to have to build. Nothing here is a string
# the generator was handed: every character came from model.aon.
for xf in gen-go gen-ts gen-sql; do
  $AONTU get '$.file' --include-root "$DIR" "$DIR/$xf.aon" > "$WORK/$xf.json" \
    || fail "$xf: transform did not evaluate"
  python3 - "$WORK/$xf.json" <<'EOF'
import json, sys
text = json.load(open(sys.argv[1]))
assert isinstance(text, str), type(text)
# Two units, separated by one blank line, and no trailing separator --
# which is the whole point of a fold over a spread.
units = text.rstrip('\n').split('\n\n')
assert 2 == len(units), len(units)
for u in units:
    lines = u.split('\n')
    assert 5 == len(lines), lines      # head, three columns, tail
    assert lines[0] and lines[-1]
EOF
  [ $? -eq 0 ] || fail "$xf: file shape wrong"
done
ok "three transforms each evaluate to ONE string: two units, no trailing separator"

# 2. The generated files are byte-identical to the goldens. This is
# the real assertion: the bytes below were produced by the unifier.
emit gen-go.aon '//' 'package acme' > "$WORK/types.go"
emit gen-ts.aon '//'                 > "$WORK/types.ts"
emit gen-sql.aon '--'                > "$WORK/schema.sql"
for f in types.go types.ts schema.sql; do
  diff -u "$DIR/expected/$f" "$WORK/$f" \
    || fail "$f drifted from expected/$f"
done
ok "three generated files match their goldens byte for byte"

# 3. The Go output is REAL Go: it compiles. A generator whose output
# merely looks right is a generator nobody trusts.
if command -v go >/dev/null 2>&1; then
  mkdir -p "$WORK/gomod" && cp "$WORK/types.go" "$WORK/gomod/"
  printf 'module gencheck\n\ngo 1.24\n' > "$WORK/gomod/go.mod"
  (cd "$WORK/gomod" && go build ./...) \
    || fail "the generated Go does not compile"
  ok "the generated Go compiles"

  # 4. ...and gofmt WOULD change it, by aligning the struct tags. That
  # is the formatter hand-off, pinned: the generator's job is correct
  # code, the formatter's job is idiomatic layout. If this ever stops
  # being true the generator has started doing layout, which is the
  # design decision to revisit, not a test to update quietly.
  [ -n "$(cd "$WORK/gomod" && gofmt -l .)" ] \
    || fail "gofmt no longer reformats the output -- see check.sh note 4"
  ok "gofmt realigns the output: layout is the formatter's job, not ours"
else
  skip "the generated Go compiles (no go toolchain)"
  skip "gofmt realigns the output (no go toolchain)"
fi

# 5. THE GAP THAT USED TO BE HERE, NOW CLOSED. Every column line once
# ended in a comma -- including the last -- because a spread can only
# put a separator AFTER each element, and this file asserted that a
# real SQL parser REFUSED the result. `join(bag, sep)` (G9 phase 2)
# puts the separator BETWEEN, so the same parser now accepts it. The
# assertion is inverted rather than deleted, because "the generated
# SQL parses" is the claim this directory exists to make.
python3 - "$WORK/schema.sql" <<'EOF'
import sqlite3, sys
sql = open(sys.argv[1]).read()
assert ",\n);" not in sql, "a trailing comma is back -- the fold regressed"
con = sqlite3.connect(":memory:")
con.executescript(sql)
have = sorted(r[0] for r in
              con.execute("select name from sqlite_master where type='table'"))
assert ["customer", "order_line"] == have, have
# `order` is reserved, which is why identifiers are quoted: the table
# is really called order_line and really has the columns the model says.
cols = [r[1] for r in con.execute('pragma table_info("order_line")')]
assert ["id", "customer_id", "total_cents"] == cols, cols
EOF
ok "the generated SQL PARSES, and creates the tables the model describes"

# 6. THE SLICES ARE REAL. Change only the `go` names in the model and
# the Go output must move while the TypeScript output must not -- the
# D5 claim that each target reads part of the model, checked rather
# than asserted.
sed 's/"Email"/"EmailAddr"/' "$DIR/model.aon" > "$WORK/model.aon"
cp "$DIR/gen-go.aon" "$DIR/gen-ts.aon" "$WORK/"
$AONTU get '$.file' --include-root "$WORK" "$WORK/gen-go.aon" | unwrap > "$WORK/go2.txt"
$AONTU get '$.file' --include-root "$WORK" "$WORK/gen-ts.aon" | unwrap > "$WORK/ts2.txt"
$AONTU get '$.file' --include-root "$DIR" "$DIR/gen-ts.aon" | unwrap > "$WORK/ts1.txt"
grep -q 'EmailAddr' "$WORK/go2.txt" \
  || fail "the go slice did not reach the Go output"
diff -q "$WORK/ts1.txt" "$WORK/ts2.txt" >/dev/null \
  || fail "a change to the go slice moved the TypeScript output"
ok "slices hold: the go rename moves Go and leaves TypeScript alone"

# 7. Generation is deterministic: the same model twice, the same bytes.
$AONTU get '$.file' --include-root "$DIR" "$DIR/gen-go.aon" | unwrap > "$WORK/again.txt"
$AONTU get '$.file' --include-root "$DIR" "$DIR/gen-go.aon" | unwrap > "$WORK/again2.txt"
diff -q "$WORK/again.txt" "$WORK/again2.txt" >/dev/null \
  || fail "two runs of the same transform differ"
ok "two runs of the same transform are byte-identical"

# 8. ADR-001: the Go port emits the same bytes. This is the check that
# matters most for a generator -- one model must not become two
# different files depending on which engine ran. It now covers the
# FOLD as well as the lines, which is where a separator or an ordering
# difference between the ports would show up first.
if command -v go >/dev/null 2>&1; then
  GOBIN="$WORK/aontu-go"
  (cd "$REPO/go" && go build -o "$GOBIN" ./cmd/aontu) \
    || fail "could not build the Go CLI"
  for xf in gen-go gen-ts gen-sql; do
    "$GOBIN" get '$.file' --include-root "$DIR" "$DIR/$xf.aon" | unwrap \
      > "$WORK/$xf.go.txt"
    $AONTU get '$.file' --include-root "$DIR" "$DIR/$xf.aon" | unwrap \
      > "$WORK/$xf.ts.txt"
    diff -u "$WORK/$xf.ts.txt" "$WORK/$xf.go.txt" \
      || fail "$xf: the two ports emit different bytes (ADR-001)"
  done
  ok "both ports emit byte-identical output for all three targets"
else
  skip "both ports emit byte-identical output (no go toolchain)"
fi


# THE MODEL TREE. The shape of this document, drawn by the one kind
# that reads no report: `view doc` walks the anchor, exactly as
# `get --keys --types` does, and stops at a depth that says how many
# keys it did not draw. The figure at the head of the README is this,
# and `--check` is the gate that keeps it true.
# The figure is what goes to STDOUT; the loss report goes to stderr.
$AONTU view doc --depth 3 "$DIR/model.aon" > "$WORK/doc.out" 2>/dev/null \
  || fail "the model tree did not draw"
diff -u "$DIR/expected/diagram-doc.txt" "$WORK/doc.out" \
  || fail "the model tree drifted"
$AONTU view doc --depth 3 --out "$DIR/expected/diagram-doc.txt" --check \
  "$DIR/model.aon" >/dev/null 2>&1 || fail "the model tree golden is stale"
$AONTU view doc --depth 3 --as svg --out "$DIR/expected/diagram-doc.svg" \
  --check "$DIR/model.aon" >/dev/null 2>&1 || fail "the model tree SVG is stale"
ok "the model tree draws and is pinned, text and SVG"

echo "all $pass checks passed"
