-- Code generated by aontu from model.aontu. DO NOT EDIT.

CREATE TABLE "customer" (
  "id" TEXT NOT NULL,
  "email" TEXT,
  "credit_cents" BIGINT
);

CREATE TABLE "order_line" (
  "id" TEXT NOT NULL,
  "customer_id" TEXT NOT NULL,
  "total_cents" BIGINT NOT NULL
);
