// Code generated by aontu from model.aon. DO NOT EDIT.

export interface Customer {
  id: string
  email?: string
  credit?: number
}

export interface Order {
  id: string
  customerId: string
  totalCents: number
}
