// Code generated by aontu from model.aon. DO NOT EDIT.

package acme

type Customer struct {
	ID string `json:"id"`
	Email string `json:"email"`
	Credit int64 `json:"credit"`
}

type Order struct {
	ID string `json:"id"`
	CustomerID string `json:"customerId"`
	TotalCents int64 `json:"totalCents"`
}
