/* Copyright (c) 2026 Richard Rodger, MIT License */

// Regenerate the build-time-inlined copies of the committed format
// grammars (ADR-059) from grammar/format/: ts/src/formatgrammars.ts and
// go/formatgrammars/. A format is a grammar, <name>.abnf, or a directory,
// <name>/, of grammars a string meets together, <name>.abnf first; the
// rules under lib/ are there for any of them to name. Run via `make
// formats`; both suites assert the copies are identical with the
// sources, so a stale copy fails rather than ships.

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..', '..')
const dir = path.join(root, 'grammar', 'format')
const godir = path.join(root, 'go', 'formatgrammars')

const text = (at) => fs.readFileSync(at, 'utf8').replaceAll('\r\n', '\n').replaceAll('\r', '\n')
const abnf = (at) => fs.readdirSync(at).filter((f) => f.endsWith('.abnf')).sort()

const formats = []
const files = []
for (const entry of fs.readdirSync(dir, { withFileTypes: true })
  .sort((a, b) => a.name < b.name ? -1 : 1)) {
  if (entry.isFile() && entry.name.endsWith('.abnf')) {
    const name = entry.name.slice(0, -'.abnf'.length)
    formats.push([name, [text(path.join(dir, entry.name))]])
    files.push(entry.name)
  }
  else if (entry.isDirectory() && 'lib' !== entry.name) {
    const name = entry.name
    const parts = abnf(path.join(dir, name))
      .sort((a, b) => (a === name + '.abnf' ? -1 : b === name + '.abnf' ? 1 : a < b ? -1 : 1))
    formats.push([name, parts.map((p) => text(path.join(dir, name, p)))])
    files.push(...parts.map((p) => name + '/' + p))
  }
}
const library = abnf(path.join(dir, 'lib'))
files.push(...library.map((f) => 'lib/' + f))

fs.rmSync(godir, { recursive: true, force: true })
for (const f of files) {
  fs.mkdirSync(path.dirname(path.join(godir, f)), { recursive: true })
  fs.writeFileSync(path.join(godir, f), text(path.join(dir, f)))
}

const ts =
  '/* Copyright (c) 2026 Richard Rodger, MIT License */\n\n' +
  '// GENERATED by ts/scripts/formats.cjs (`make formats`) from\n' +
  '// grammar/format/ — DO NOT EDIT. The grammars are the source;\n' +
  '// ts/test/formatgrammar.test.ts asserts this copy is identical with\n' +
  '// them.\n\n' +
  'const FORMAT_GRAMMARS = new Map<string, string[]>(' +
  JSON.stringify(formats, null, 2) + ')\n\n' +
  'const FORMAT_LIBRARY: string = ' +
  JSON.stringify(library.map((f) => text(path.join(dir, 'lib', f))).join('\n')) + '\n\n' +
  'export { FORMAT_GRAMMARS, FORMAT_LIBRARY }\n'

fs.writeFileSync(path.join(root, 'ts', 'src', 'formatgrammars.ts'), ts)
console.log('formats: wrote ' + formats.length + ' formats, ' + files.length +
  ' grammars, to ts/src/formatgrammars.ts and go/formatgrammars/')
