/* Copyright (c) 2026 Richard Rodger, MIT License */

// Regenerate test/spec/files/match-corpus.tsv, the differential corpus
// of aontu's own pattern matcher (ADR-060): seeded patterns over the
// u-mode vocabulary, well-formed and not, each with three texts, and
// what each port's matcher says of them. The verdicts come from the
// committed TypeScript build; go/match_corpus_test.go and
// ts/test/match-corpus.test.ts recompute every one, so a corpus is
// committed only once both ports reproduce it. Run via
// `node ts/scripts/matchcorpus.cjs` after `make build-ts`.

'use strict'

const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..', '..')
const OUT = path.join(ROOT, 'test', 'spec', 'files', 'match-corpus.tsv')
const { compilePattern, patternMatches, exportForm, importForm, ecmaWhy } =
  require(path.join(ROOT, 'ts', 'dist', 'regex'))

const SEED = 20261009
const PATTERNS = 700

// mulberry32: the low bits of a plain linear congruence repeat too soon.
let seed = SEED
const rnd = (n) => {
  seed = (seed + 0x6D2B79F5) | 0
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed)
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
  return ((t ^ (t >>> 14)) >>> 0) % n
}
const pick = (xs) => xs[rnd(xs.length)]

const ATOMS = ['a', 'b', 'A', '.', '\\d', '\\w', '\\s', '\\S', '\\D', '\\W', '[ab]', '[^a]', '[a-c]',
  '[\\s\\d]', '[^\\S]', '[\\S]', '[\\w-]', '[\\-a]', '[a\\-]', '[]', '[^]', '\\b', '\\B', '^', '$',
  'é', '\\u{1F600}', '\u{1F600}', '[\\u{1F600}-\\u{1F64F}]', '\\uD83D\\uDE00', '\\uD83D', '\\u00e9',
  '\\x41', '\\cJ', '\\cz', '\\0', '[\\b]', '\\/', '\\.', '\\n', '\\t', '\\r', '\\f', '\\v',
  '\\p{L}', '\\P{Lu}', '\\p{Nd}', '\\p{gc=Ll}', '\\p{General_Category=Letter}', '\\p{sc=Grek}',
  '\\p{Script=Latin}', '\\p{scx=Arab}', '\\p{Script_Extensions=Hira}', '\\P{scx=Grek}',
  '\\p{Any}', '\\p{ASCII}', '\\p{Assigned}', '\\p{Alphabetic}', '\\p{White_Space}', '\\p{Emoji}',
  '[\\p{L}\\d]', '[^\\p{Lu}]', '\\A', '\\z', '(?<n0>x)']
// What re() refuses: syntax u mode does not read, and what no regular
// language holds.
const REFUSED = ['(?=a)', '(?!a)', '(?<=b)', '(?<!b)', '\\1', '\\k<n0>', '(?i:a)', '(?-i:a)',
  '(?ims-:a)', '(?ii:a)', '(?-:a)', '(?x:a)', '{', '}', ']', ')', '|', '\\q', '\\-', '\\Z', '[z-a]',
  'a{3,2}', 'a{,2}', '\\p{Bogus}', '\\p{lu}', '\\p{L', '\\pL', '(?<1>x)', '\\u{110000}', '\\u{}',
  '\\u12', '\\x4', '[\\d-z]', '[a-\\d]', '\\c1', '\\00', '[\\1]', '[\\A]', '\\']
const QUANT = ['', '', '', '', '*', '+', '?', '{2}', '{1,3}', '{0,}', '{2,}', '*?', '+?', '??',
  '{0}', '{1,1}?']
const LARGE = ['{99999999999}', '{1001}', '{400}']
const ASSERTIONS = ['\\b', '\\B', '^', '$', '\\A', '\\z']
const CHARS = ['a', 'b', 'A', 'Z', '1', '_', ' ', '\n', '\r', '\t', ' ', ' ', 'é', 'Ω',
  'ж', '١', 'ا', '\u{1F600}', '/', '\b', '、', '͸', '-', '.']

function pattern(depth) {
  let out = ''
  for (let k = 1 + rnd(4); 0 < k; k--) {
    const group = 0 < depth && 0 === rnd(4)
    const atom = group ? pick(['(?:', '(', '(?<n' + rnd(2) + '>']) + pattern(depth - 1) + ')' :
      pick(0 === rnd(16) ? REFUSED : ATOMS)
    // A quantified assertion is refused, so it is kept rare.
    const assertion = ASSERTIONS.includes(atom) && 0 !== rnd(16)
    out += atom + (assertion ? '' : pick(0 === rnd(40) ? LARGE : QUANT))
  }
  return 0 < depth && 0 === rnd(5) ? out + '|' + pattern(depth - 1) : out
}

function text() {
  let s = ''
  for (let k = rnd(7); 0 < k; k--) {
    s += pick(CHARS)
  }
  return s
}

// What re() says of each text, as one digit a text, or why it refuses.
function verdict(p, texts) {
  const [prog, why] = compilePattern(p, 'aontu')
  return undefined === prog ? '!' + why : texts.map((s) => patternMatches(prog, s) ? '1' : '0').join('')
}

const form = ([out, why]) => JSON.stringify('' === why ? out : '!' + why)

const rows = []
const seen = new Set()
while (rows.length < PATTERNS) {
  const p = pattern(2)
  if (seen.has(p)) {
    continue
  }
  seen.add(p)
  const texts = [text(), text(), text()]
  const ecma = ecmaWhy(p)
  rows.push([JSON.stringify(p), JSON.stringify(texts), verdict(p, texts), form(exportForm(p)),
    form(importForm(p)), '' === ecma ? 'ok' : '!' + ecma].join('\t'))
}

const HEAD = [
  '# Differential corpus of aontu\'s own pattern matcher (ADR-060).',
  '# GENERATED by ts/scripts/matchcorpus.cjs (seed ' + SEED + '), then committed.',
  '#',
  '# Columns, the first two and the fourth and fifth as JSON strings:',
  '#   pattern <TAB> texts <TAB> match <TAB> export <TAB> import <TAB> regex',
  '#   match   re()\'s verdict on each text, 1 admitted and 0 not, or',
  '#           "!" and why re() refuses the pattern;',
  '#   export  the ECMA-262 text the exporter writes for it, or "!" and why;',
  '#   import  the re() source the importer writes for it read as an',
  '#           ECMA-262 pattern, or "!" and why it is dropped;',
  '#   regex   format("regex")\'s verdict: ok, or "!" and why.',
  '#',
  '# Both ports recompute every column and must reproduce it byte for',
  '# byte, so a drift in the parser, the compiler, the matcher or the',
  '# rewriting fails in whichever port drifted. The patterns are seeded,',
  '# never drawn at test time: to extend the corpus, change the seed or',
  '# the vocabulary, regenerate, and commit only if both ports pass.',
]
fs.writeFileSync(OUT, HEAD.join('\n') + '\n' + rows.join('\n') + '\n')
console.log('matchcorpus: ' + rows.length + ' patterns, ' +
  rows.filter((r) => r.split('\t')[2].startsWith('!')).length + ' refused, ' +
  fs.statSync(OUT).size + ' bytes')
