/* Copyright (c) 2026 Richard Rodger, MIT License */

// Stage the published JSON Schema meta-schemas, vendored in
// test/vectors/json-schema-spec/, into ts/src/metaschemas.ts and
// go/metaschemas/, each document under the URI its own identifier
// gives, with the licence they are redistributed under. The Go half must
// be a committed copy: //go:embed cannot read above its own package
// directory. Run via `make metaschemas`; both suites assert each copy is
// identical with the vendored documents, so a stale copy fails rather
// than ships.

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..', '..')
const dir = path.join(root, 'test', 'vectors', 'json-schema-spec')
const godir = path.join(root, 'go', 'metaschemas')
const text = (at) => fs.readFileSync(at, 'utf8').replaceAll('\r\n', '\n')

const walk = (at) => fs.readdirSync(at, { withFileTypes: true })
  .sort((a, b) => a.name < b.name ? -1 : 1)
  .flatMap((e) => e.isDirectory() ? walk(path.join(at, e.name)).map((f) => e.name + '/' + f) : [e.name])
const docs = walk(dir).filter((f) => f.endsWith('.json')).map((f) => {
  const t = text(path.join(dir, f))
  const doc = JSON.parse(t)
  return [(doc.$id ?? doc.id).replace(/#$/, ''), f, t]
})
const license = text(path.join(dir, 'LICENSE'))

fs.rmSync(godir, { recursive: true, force: true })
for (const [, f, t] of docs) {
  fs.mkdirSync(path.dirname(path.join(godir, f)), { recursive: true })
  fs.writeFileSync(path.join(godir, f), t)
}
fs.writeFileSync(path.join(godir, 'LICENSE'), license)
fs.writeFileSync(path.join(godir, 'index.tsv'), docs.map(([uri, f]) => uri + '\t' + f + '\n').join(''))

fs.writeFileSync(path.join(root, 'ts', 'src', 'metaschemas.ts'),
  '/* Copyright (c) 2026 Richard Rodger, MIT License */\n\n' +
  '// GENERATED by ts/scripts/metaschemas.cjs (`make metaschemas`) from\n' +
  '// test/vectors/json-schema-spec/, which is the source: do not edit.\n' +
  '// ts/test/metaschemas.test.ts asserts the copy is identical.\n\n' +
  'const META_SCHEMAS: Record<string, string> = ' +
  JSON.stringify(Object.fromEntries(docs.map(([uri, , t]) => [uri, t])), null, 2) + '\n\n' +
  '// The licence the meta-schemas are redistributed under.\n' +
  'const META_SCHEMA_LICENSE: string = ' + JSON.stringify(license) + '\n\n' +
  'export { META_SCHEMAS, META_SCHEMA_LICENSE }\n')
console.log('metaschemas: staged ' + docs.length + ' meta-schemas to ts/src/metaschemas.ts and go/metaschemas/')
