/* Copyright (c) 2021-2026 Richard Rodger, MIT License */

// Regenerate the build-time-inlined copies of the signature
// declaration (docs/design/SIGNATURES.0.md): ts/src/sigdecl.ts and
// go/sigdecl.txt, both byte-derived from test/spec/signature.tsv.
// Run via `make sig`; the suites assert the copies are identical
// with the shared file, so a stale copy fails loudly.

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..', '..')
const src = path.join(root, 'test', 'spec', 'signature.tsv')
const text = fs.readFileSync(src, 'utf8')

const ts = '/* Copyright (c) 2021-2026 Richard Rodger, MIT License */\n\n' +
  '// GENERATED by ts/scripts/sigdecl.cjs (`make sig`) from\n' +
  '// test/spec/signature.tsv — DO NOT EDIT. The declaration is the\n' +
  '// source (docs/design/SIGNATURES.0.md); ts/test/sig.test.ts asserts\n' +
  '// this copy is identical with the shared file.\n\n' +
  'const SIGDECL: string =\n' +
  JSON.stringify(text) + '\n\n' +
  'export { SIGDECL }\n'

fs.writeFileSync(path.join(root, 'ts', 'src', 'sigdecl.ts'), ts)
fs.writeFileSync(path.join(root, 'go', 'sigdecl.txt'), text)
console.log('sigdecl: wrote ts/src/sigdecl.ts and go/sigdecl.txt')
