/* Copyright (c) 2026 Richard Rodger, MIT License */

// Stage the JSON Schema vocabulary table, grammar/jsonschema/
// vocabularies.tsv, into ts/src/vocabularies.ts and go/vocabularies.tsv.
// The Go half must be a committed copy: //go:embed cannot read above its
// own package directory. Run via `make vocabularies`; both suites assert
// each copy is identical with the table, so a stale copy fails rather
// than ships.

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..', '..')
const table = fs.readFileSync(path.join(root, 'grammar', 'jsonschema', 'vocabularies.tsv'), 'utf8')
  .replaceAll('\r\n', '\n')

fs.writeFileSync(path.join(root, 'go', 'vocabularies.tsv'), table)
fs.writeFileSync(path.join(root, 'ts', 'src', 'vocabularies.ts'),
  '/* Copyright (c) 2026 Richard Rodger, MIT License */\n\n' +
  '// GENERATED by ts/scripts/vocabularies.cjs (`make vocabularies`) from\n' +
  '// grammar/jsonschema/vocabularies.tsv, which is the source: do not\n' +
  '// edit. ts/test/vocabularies.test.ts asserts the copy is identical.\n\n' +
  'const VOCABULARY_TABLE: string = ' + JSON.stringify(table) + '\n\n' +
  'export { VOCABULARY_TABLE }\n')
const count = table.split('\n').filter((l) => 4 < l.split('\t').length).length - 1
console.log('vocabularies: staged ' + count +
  ' vocabularies to ts/src/vocabularies.ts and go/vocabularies.tsv')
