graph LR
  n___catalog_domains_identity_services_auth["auth"]
  n___catalog_domains_identity_services_directory["directory"]
  n___catalog_domains_payments_services_ledger["ledger"]
  n___catalog_domains_payments_services_payments["payments"]
  n___catalog_domains_payments_services_risk["risk"]
  n___catalog_domains_platform_services_email["email"]
  n___catalog_domains_platform_services_gateway["gateway"]
  n___catalog_domains_platform_services_notify["notify"]
  n___catalog_domains_identity_services_auth -->|"dependsOn"| n___catalog_domains_identity_services_directory
  n___catalog_domains_payments_services_payments -->|"dependsOn"| n___catalog_domains_identity_services_auth
  n___catalog_domains_payments_services_payments -->|"dependsOn"| n___catalog_domains_payments_services_ledger
  n___catalog_domains_payments_services_payments -->|"dependsOn"| n___catalog_domains_payments_services_risk
  n___catalog_domains_payments_services_payments -->|"dependsOn"| n___catalog_domains_platform_services_notify
  n___catalog_domains_payments_services_risk -->|"dependsOn"| n___catalog_domains_identity_services_directory
  n___catalog_domains_platform_services_gateway -->|"dependsOn"| n___catalog_domains_identity_services_auth
  n___catalog_domains_platform_services_gateway -->|"dependsOn"| n___catalog_domains_payments_services_payments
  n___catalog_domains_platform_services_notify -->|"dependsOn"| n___catalog_domains_platform_services_email
