graph LR
  n___pipeline_jobs_audit["audit"]
  n___pipeline_jobs_extract["extract"]
  n___pipeline_jobs_load["load"]
  n___pipeline_jobs_transform["transform"]
  n___pipeline_jobs_extract -->|"feeds"| n___pipeline_jobs_transform
  n___pipeline_jobs_transform -->|"feeds"| n___pipeline_jobs_audit
  n___pipeline_jobs_transform -->|"feeds"| n___pipeline_jobs_load
