/* Copyright (c) 2025 Richard Rodger, MIT License */

// GENERATED by ts/scripts/aontu.cjs (`make aontu`) from aontu/ -
// DO NOT EDIT. The tree is the source; go/aontumodel_test.go
// asserts go/aontumodel/ is identical with it.

package aontu

import _ "embed"

const aontuScheme = "aontu:"

//go:embed aontumodel/lang/markdown.aon
var aontuLangMarkdown string

//go:embed aontumodel/lang/text.aon
var aontuLangText string

//go:embed aontumodel/profile/profile.aon
var aontuProfile string

//go:embed aontumodel/system/system.aon
var aontuSystem string

//go:embed aontumodel/view/view.aon
var aontuView string

var aontuSources = map[string]string{
	"aontu:lang/markdown": aontuLangMarkdown,
	"aontu:lang/text":     aontuLangText,
	"aontu:profile":       aontuProfile,
	"aontu:system":        aontuSystem,
	"aontu:view":          aontuView,
}

// aontuModels names the set the scheme serves, sorted, for the
// not-found message: a typo in an aontu: name is refused naming the
// set rather than searched for on disk.
var aontuModels = []string{
	"aontu:lang/markdown",
	"aontu:lang/text",
	"aontu:profile",
	"aontu:system",
	"aontu:view",
}
