/* Copyright (c) 2025 Richard Rodger, MIT License */


package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	aontu "github.com/aontu-lang/aontu/go"
)

const pkgToolSource = "name: string\nport: *8080 | integer\n"

func pkgRun(args ...string) (string, string, int) {
	var out, errw bytes.Buffer
	code := run(append([]string{"pkg"}, args...),
		strings.NewReader(""), &out, &errw, false)
	return out.String(), errw.String(), code
}

// pkgProject builds a project with the given dep block.
func pkgProject(t *testing.T, dep string) string {
	t.Helper()
	dir := t.TempDir()
	pkgWrite(t, filepath.Join(dir, "pkg.aontu"),
		"pkg: {path: \"corp.example/app\"}\ndep: {"+dep+"}\n")
	return dir
}

func pkgVendorTree(t *testing.T, dir, path string, files map[string]string) {
	t.Helper()
	p := filepath.Join(append([]string{dir, "aontu_meta", "vendor"},
		strings.Split(path, "/")...)...)
	if err := os.MkdirAll(p, 0o755); nil != err {
		t.Fatal(err)
	}
	for name, src := range files {
		pkgWrite(t, filepath.Join(p, name), src)
	}
}

func pkgWrite(t *testing.T, file, src string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(file), 0o755); nil != err {
		t.Fatal(err)
	}
	if err := os.WriteFile(file, []byte(src), 0o600); nil != err {
		t.Fatal(err)
	}
}

var pkgServiceFiles = map[string]string{
	"pkg.aontu":     "pkg: {path: \"corp.example/schemas/service\", main: \"service.aontu\"}\n",
	"service.aontu": pkgToolSource,
}

func TestPkgTidyWritesCanonicalLockfile(t *testing.T) {
	dir := pkgProject(t, "\"corp.example/schemas/service\": {v: \"1.4.2\"}")
	pkgVendorTree(t, dir, "corp.example/schemas/service", pkgServiceFiles)

	out, errw, code := pkgRun("tidy", dir)
	if 0 != code {
		t.Fatalf("tidy = %d: %s", code, errw)
	}
	if !strings.Contains(out, "verdict: ok") ||
		!strings.Contains(out, "corp.example/schemas/service 1.4.2 aon1-") {
		t.Fatalf("want ok:\n%s", out)
	}

	data, err := os.ReadFile(filepath.Join(dir, "aontu_meta", "pkg-lock.aontu"))
	if nil != err {
		t.Fatal(err)
	}
	lock := string(data)
	if !strings.HasPrefix(lock, "# pkg-lock.aontu (generated by") {
		t.Fatalf("want the generated-file header:\n%s", lock)
	}
	line := strings.Split(lock, "\n")[1]
	v, _ := aontu.New().Unify(pkgToolSource)
	tree := filepath.Join(dir, "aontu_meta", "vendor", "corp.example", "schemas", "service")
	want := "{\"lock\":{\"corp.example/schemas/service\":{\"archive\":\"" +
		aontu.ArchiveOf(tree).Digest + "\",\"canon\":\"" +
		aontu.CanonHash(v) + "\",\"v\":\"1.4.2\"}}}"
	if line != want {
		t.Fatalf("lock line\n want: %s\n got:  %s", want, line)
	}
	var parsed map[string]any
	if err := json.Unmarshal([]byte(line), &parsed); nil != err {
		t.Fatalf("the canonical line must be JSON: %v", err)
	}
}

func TestPkgTidySelectsMaximumOfMinima(t *testing.T) {
	// MINIMUM VERSION SELECTION: the project asks for 1.2.0 of geo and
	// the package it depends on asks for 1.10.0, so 1.10.0 is selected —
	// and 1.10.0 is above 1.2.0 by NUMBER, which string order gets
	// wrong.
	dir := pkgProject(t,
		"\"corp.example/s\": {v: \"1.2.0\"}, \"corp.example/geo\": {v: \"1.2.0\"}")
	pkgVendorTree(t, dir, "corp.example/s", map[string]string{
		"pkg.aontu": "pkg: {path: \"corp.example/s\"}\n" +
			"dep: {\"corp.example/geo\": {v: \"1.10.0\"}}\n",
		"main.aontu": pkgToolSource,
	})
	pkgVendorTree(t, dir, "corp.example/geo", map[string]string{
		"pkg.aontu":  "pkg: {path: \"corp.example/geo\"}\n",
		"main.aontu": "region: string\n",
	})

	out, errw, code := pkgRun("tidy", dir)
	if 0 != code {
		t.Fatalf("tidy = %d: %s", code, errw)
	}
	if !strings.Contains(out, "corp.example/geo 1.10.0 aon1-") {
		t.Fatalf("want geo at 1.10.0:\n%s", out)
	}
}

func TestPkgTidyRefusesToLockWhatItCannotSee(t *testing.T) {
	// A lockfile naming a package nobody has is a lie, so no lockfile is
	// written at all.
	dir := pkgProject(t, "\"corp.example/absent\": {v: \"1.0.0\"}")
	out, _, code := pkgRun("tidy", dir)
	if 1 != code {
		t.Fatalf("want 1, got %d:\n%s", code, out)
	}
	if !strings.Contains(out, "corp.example/absent: not fetched (run: aontu sync)") {
		t.Fatalf("want the fetch instruction:\n%s", out)
	}
	if _, err := os.Stat(filepath.Join(dir, "aontu_meta", "pkg-lock.aontu")); nil == err {
		t.Fatal("no lockfile may be written")
	}
}

func TestPkgTidyRefusesAForbiddenFile(t *testing.T) {
	dir := pkgProject(t, "\"corp.example/schemas/service\": {v: \"1.4.2\"}")
	pkgVendorTree(t, dir, "corp.example/schemas/service", pkgServiceFiles)
	pkgWrite(t, filepath.Join(dir, "aontu_meta", "vendor", "corp.example", "schemas",
		"service", "hook.sh"), "echo\n")
	out, _, code := pkgRun("tidy", dir)
	if 4 != code || !strings.Contains(out, "hook.sh: not admitted in a package") {
		t.Fatalf("forbidden = %d:\n%s", code, out)
	}
}

func TestPkgVendorMaterialisesTheClosure(t *testing.T) {
	// From the CACHE, keyed by the hash the lockfile pins and the
	// package path: that is what content-addressed means, and why
	// `vendor` needs a lockfile while `tidy` needs a store.
	dir := pkgProject(t, "")
	v, _ := aontu.New().Unify(pkgToolSource)
	hash := aontu.CanonHash(v)

	xdg := filepath.Join(dir, "xdg")
	cachedir := filepath.Join(xdg, "aontu", "pkg", "store", hash, "corp.example", "schemas", "service")
	pkgWrite(t, filepath.Join(cachedir, "pkg.aontu"), pkgServiceFiles["pkg.aontu"])
	pkgWrite(t, filepath.Join(cachedir, "service.aontu"), pkgToolSource)
	pkgWrite(t, filepath.Join(dir, "aontu_meta", "pkg-lock.aontu"),
		"# pkg-lock.aontu (generated by `aontu sync`; do not edit)\n"+
			"{\"lock\":{\"corp.example/schemas/service\":{\"archive\":\"\",\"canon\":\""+hash+
			"\",\"v\":\"1.4.2\"}}}\n")

	t.Setenv("XDG_CACHE_HOME", xdg)
	out, errw, code := pkgRun("vendor", dir)
	if 0 != code {
		t.Fatalf("vendor = %d: %s\n%s", code, errw, out)
	}
	if _, err := os.Stat(filepath.Join(dir, "aontu_meta", "vendor", "corp.example",
		"schemas", "service", "service.aontu")); nil != err {
		t.Fatalf("want the package materialised: %v", err)
	}
}

func TestPkgVendorReportsWhatNoStoreHas(t *testing.T) {
	dir := pkgProject(t, "")
	pkgWrite(t, filepath.Join(dir, "aontu_meta", "pkg-lock.aontu"),
		"{\"lock\":{\"nope.example/x\":{\"canon\":\"x\",\"archive\":\"\",\"v\":\"1\"},"+
			"\"not-a-module\":{\"canon\":\"y\",\"archive\":\"\",\"v\":\"1\"}}}\n")
	out, _, code := pkgRun("vendor", dir)
	if 1 != code {
		t.Fatalf("want 1, got %d:\n%s", code, out)
	}
	for _, want := range []string{"nope.example/x: not fetched", "not-a-module: not fetched"} {
		if !strings.Contains(out, want) {
			t.Fatalf("want %q:\n%s", want, out)
		}
	}
}

func TestPkgNetworkSubcommandsTakeThePkgOptions(t *testing.T) {
	if _, errw, code := pkgRun("outdated", "--against", "x", "."); 2 != code ||
		!strings.Contains(errw, "--against is a manifest option") {
		t.Fatalf("outdated --against = %d: %s", code, errw)
	}
	if _, _, code := pkgRun("serve", "--listen"); 2 != code {
		t.Fatalf("serve --listen = %d", code)
	}
}

func TestPkgArguments(t *testing.T) {
	if out, _, code := pkgRun("--help"); 0 != code ||
		!strings.Contains(out, "aontu pkg") {
		t.Fatalf("--help = %d:\n%s", code, out)
	}
	for _, args := range [][]string{{}, {"nope"}, {"tidy", "a", "b"}} {
		if _, errw, code := pkgRun(args...); 2 != code ||
			!strings.Contains(errw, "pkg needs one of tidy, verify") {
			t.Fatalf("%v = %d: %s", args, code, errw)
		}
	}
	if _, errw, code := pkgRun("--format", "yaml", "tidy"); 2 != code ||
		!strings.Contains(errw, "text or json") {
		t.Fatalf("bad format = %d: %s", code, errw)
	}
	if _, errw, code := pkgRun("--format"); 2 != code ||
		!strings.Contains(errw, "text or json") {
		t.Fatalf("missing format value = %d: %s", code, errw)
	}
	if _, errw, code := pkgRun("--nope", "tidy"); 2 != code ||
		!strings.Contains(errw, "unknown pkg option") {
		t.Fatalf("bad option = %d: %s", code, errw)
	}
	for _, flag := range []string{"--to", "--base", "--key", "--token", "--write",
		"--listen", "--upstream"} {
		if _, errw, code := pkgRun("tidy", flag); 2 != code ||
			!strings.Contains(errw, flag+" needs a value") {
			t.Fatalf("%s = %d: %s", flag, code, errw)
		}
	}
	// Every option the table knows parses, whatever the subcommand
	// does with it.
	if _, _, code := pkgRun("--frozen", "--yes", "--to", "x", "--key", "k",
		"--token", "t", "--write", "w", "--listen", "l", "--base", "b",
		"--upstream", "u", "tree", t.TempDir()); 0 != code {
		t.Fatalf("the option table = %d", code)
	}
	// A verb that reads a document takes the trust options.
	for _, flag := range [][]string{{"--trust", "none"}, {"--include-root", "."},
		{"--text-ext", "md"}} {
		args := append(append([]string{}, flag...), "tidy")
		if _, errw, code := pkgRun(args...); 2 == code &&
			strings.Contains(errw, "unknown pkg option") {
			t.Fatalf("%v refused: %s", flag, errw)
		}
	}
	if _, errw, code := pkgRun("--trust", "everything", "tidy"); 2 != code ||
		!strings.Contains(errw, "--trust needs") {
		t.Fatalf("bad trust = %d: %s", code, errw)
	}
	// `--against` gates a manifest and means nothing to the others;
	// accepting it there would say it had been honoured.
	if _, errw, code := pkgRun("tidy", "--against", "x"); 2 != code ||
		!strings.Contains(errw, "--against is a manifest option") {
		t.Fatalf("against on tidy = %d: %s", code, errw)
	}
	if _, errw, code := pkgRun("manifest", "--against"); 2 != code ||
		!strings.Contains(errw, "--against needs a value") {
		t.Fatalf("missing against value = %d: %s", code, errw)
	}
}

// The command's own manifest surface: the text body, the JSON envelope
// and the exit classes. What the report SAYS is proved against the
// package API in go/pkg_test.go, with ts/test/pkg.test.ts as the
// cross-port twin.
func TestPkgManifestCommand(t *testing.T) {
	pub := func(version, src string, extra string) string {
		dir := t.TempDir()
		decl := "pkg: {path: \"corp.example/schemas/service\""
		if "" != version {
			decl += ", version: \"" + version + "\""
		}
		decl += ", main: \"service.aontu\"}\npublish: public\n" + extra
		pkgWrite(t, filepath.Join(dir, "pkg.aontu"), decl)
		if "" != src {
			pkgWrite(t, filepath.Join(dir, "service.aontu"), src)
		}
		return dir
	}

	out, _, code := pkgRun("manifest", pub("1.1.0", pkgToolSource,
		"dep: {\"alias:old\": {pkg: \"corp.example/core\", v: \"1.0.0\"}}\n"+
			"retract: [\"1.0.9\"]\nmoved: \"corp.example/schemas/svc\"\n"))
	if 0 != code {
		t.Fatalf("manifest = %d:\n%s", code, out)
	}
	for _, want := range []string{
		"verdict: ok",
		"corp.example/schemas/service 1.1.0 public",
		"archive: sha256:",
		"module: corp.example/schemas/service service.aontu aon1-",
		"dep: alias:old 1.0.0 (corp.example/core)",
		"retract: 1.0.9",
		"moved: corp.example/schemas/svc",
		"file: service.aontu sha256:",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("manifest text lacks %q:\n%s", want, out)
		}
	}

	// A package that declares no version has nothing to publish under,
	// and that is an error class rather than a missing fetch.
	miss, _, code := pkgRun("manifest", pub("", pkgToolSource, ""))
	if 4 != code || !strings.Contains(miss, "pkg.version: missing") {
		t.Fatalf("no version = %d:\n%s", code, miss)
	}

	bad := pub("1.1.0", pkgToolSource, "")
	pkgWrite(t, filepath.Join(bad, "build.sh"), "echo\n")
	if out, _, code := pkgRun("manifest", bad); 4 != code ||
		!strings.Contains(out, "build.sh: not admitted in a package") {
		t.Fatalf("forbidden = %d:\n%s", code, out)
	}

	// The gate's exit class is Subsume's, because the gate IS a
	// subsumption check.
	prior := pub("1.0.0", pkgToolSource, "")
	next := pub("1.1.0", pkgToolSource+"region: *\"eu\" | string\n", "")
	gated, _, code := pkgRun("manifest", "--against", prior, next)
	if 1 != code || !strings.Contains(gated, "verdict: breaking") ||
		!strings.Contains(gated, "$.region: ") {
		t.Fatalf("gate = %d:\n%s", code, gated)
	}

	undecided, _, code := pkgRun("manifest",
		"--against", pub("1.0.0", "a: min(1)\n", ""),
		pub("1.1.0", "a: must(min(1), \"m\")\n", ""))
	if 3 != code || !strings.Contains(undecided, "verdict: undecided") {
		t.Fatalf("undecided gate = %d:\n%s", code, undecided)
	}

	jsonOut, _, code := pkgRun("manifest", "--format", "json",
		pub("1.1.0", pkgToolSource, ""))
	if 0 != code {
		t.Fatalf("manifest json = %d:\n%s", code, jsonOut)
	}
	var report struct {
		Aontu struct {
			Verb string `json:"verb"`
		} `json:"aontu"`
		Manifest struct {
			Modules []struct {
				Canon string `json:"canon"`
			} `json:"modules"`
		} `json:"manifest"`
		Verdict string `json:"verdict"`
	}
	if err := json.Unmarshal([]byte(jsonOut), &report); nil != err {
		t.Fatalf("json: %v\n%s", err, jsonOut)
	}
	if "pkg manifest" != report.Aontu.Verb || "ok" != report.Verdict ||
		1 != len(report.Manifest.Modules) ||
		!strings.HasPrefix(report.Manifest.Modules[0].Canon, "aon1-") {
		t.Fatalf("report %+v", report)
	}
}

func TestPkgTidyJSONIsTheReport(t *testing.T) {
	dir := pkgProject(t, "\"corp.example/schemas/service\": {v: \"1.4.2\"}")
	pkgVendorTree(t, dir, "corp.example/schemas/service", pkgServiceFiles)

	out, _, code := pkgRun("tidy", "--format", "json", dir)
	if 0 != code {
		t.Fatalf("tidy json = %d:\n%s", code, out)
	}
	var report struct {
		Aontu struct {
			Verb string `json:"verb"`
		} `json:"aontu"`
		Lock []struct {
			Key string `json:"key"`
		} `json:"lock"`
		Missing []string `json:"missing"`
		Verdict string   `json:"verdict"`
	}
	if err := json.Unmarshal([]byte(out), &report); nil != err {
		t.Fatalf("not JSON: %v\n%s", err, out)
	}
	if "pkg tidy" != report.Aontu.Verb || "ok" != report.Verdict ||
		1 != len(report.Lock) ||
		"corp.example/schemas/service" != report.Lock[0].Key {
		t.Fatalf("bad report: %+v", report)
	}
}

func TestPkgVerifyCommand(t *testing.T) {
	dir := pkgProject(t, "\"corp.example/schemas/service\": {v: \"1.4.2\"}")
	pkgVendorTree(t, dir, "corp.example/schemas/service", pkgServiceFiles)
	// Before the lockfile exists there is nothing to check, which is a
	// refusal and not a pass: the repair is a sync, and the line says so.
	if out, _, code := pkgRun("verify", dir); 1 != code ||
		!strings.Contains(out, "verdict: unlocked") ||
		!strings.Contains(out,
			"corp.example/schemas/service: not in the lockfile (run: aontu sync)") {
		t.Fatalf("unlocked verify = %d: %s", code, out)
	}

	if _, errw, code := pkgRun("tidy", dir); 0 != code {
		t.Fatalf("tidy = %d: %s", code, errw)
	}
	lock, err := os.ReadFile(filepath.Join(dir, "aontu_meta", "pkg-lock.aontu"))
	if nil != err {
		t.Fatal(err)
	}

	out, errw, code := pkgRun("verify", dir)
	if 0 != code || !strings.Contains(out, ": verified") {
		t.Fatalf("clean verify = %d: %s%s", code, out, errw)
	}

	svc := filepath.Join(dir, "aontu_meta", "vendor", "corp.example", "schemas",
		"service", "service.aontu")
	pkgWrite(t, svc, strings.Replace(pkgToolSource, "8080", "9090", 1))

	// BYTES BEFORE MEANING: the archive pin is what moves first.
	out, _, code = pkgRun("verify", dir)
	if 1 != code || !strings.Contains(out, "verdict: mismatch") ||
		!strings.Contains(out, "pinned archive sha256:") ||
		!strings.Contains(out, "but the store holds sha256:") {
		t.Fatalf("tampered verify = %d: %s", code, out)
	}
	now, err := os.ReadFile(filepath.Join(dir, "aontu_meta", "pkg-lock.aontu"))
	if nil != err || string(lock) != string(now) {
		t.Fatal("verify rewrote the lockfile")
	}

	// With the archive pin made to agree, the meaning is what is judged.
	repin := func(src string) {
		pkgWrite(t, svc, src)
		arch := aontu.ArchiveOf(filepath.Dir(svc)).Digest
		i := strings.Index(string(lock), "\"archive\":\"")
		j := strings.Index(string(lock)[i+11:], "\"")
		pkgWrite(t, filepath.Join(dir, "aontu_meta", "pkg-lock.aontu"),
			string(lock)[:i+11]+arch+string(lock)[i+11+j:])
	}
	repin("a: 1\na: 2\n")
	if out, _, code = pkgRun("verify", dir); 1 != code ||
		!strings.Contains(out, "it does not evaluate") {
		t.Fatalf("broken verify = %d: %s", code, out)
	}
	repin(strings.Replace(pkgToolSource, "8080", "9090", 1))
	if out, _, code = pkgRun("verify", dir); 1 != code ||
		!strings.Contains(out, "but the store means aon1-") {
		t.Fatalf("moved verify = %d: %s", code, out)
	}

	// A kept manifest is a pin of its own.
	repin(pkgToolSource)
	tree := filepath.Dir(svc)
	a := aontu.ArchiveOf(tree)
	pkgWrite(t, filepath.Join(tree, "aontu_meta", "manifest.aontu"),
		"{\"archive\":{\"digest\":\""+a.Digest+"\",\"files\":[{\"path\":\"pkg.aontu\",\"digest\":\"sha256:0\",\"size\":1}]}}")
	if _, _, code := pkgRun("tidy", dir); 0 != code {
		t.Fatal("retidy")
	}
	if out, _, code = pkgRun("verify", dir); 1 != code ||
		!strings.Contains(out, "pinned manifest") {
		t.Fatalf("manifest verify = %d: %s", code, out)
	}

	// And TIDY refuses to pin a broken module, rather than writing the
	// hash of nil.
	pkgWrite(t, svc, "a: 1\na: 2\n")
	if out, _, code = pkgRun("tidy", dir); 4 != code ||
		!strings.Contains(out, "does not evaluate on its own; nothing to pin") {
		t.Fatalf("tidy over a broken module = %d: %s", code, out)
	}
}

func TestPkgVerifyReportsMissingCommand(t *testing.T) {
	dir := t.TempDir()
	pkgWrite(t, filepath.Join(dir, "aontu_meta", "pkg-lock.aontu"),
		"{\"lock\":{\"corp.example/absent\":{\"archive\":\"\",\"canon\":\"aon1-x\",\"v\":\"1\"}}}\n")
	out, _, code := pkgRun("verify", dir)
	if 1 != code || !strings.Contains(out, "verdict: missing") ||
		!strings.Contains(out, "corp.example/absent: not fetched (run: aontu sync)") {
		t.Fatalf("missing verify = %d: %s", code, out)
	}
}

func TestPkgRefreezeAndTreeCommands(t *testing.T) {
	dir := pkgProject(t,
		"\"corp.example/s\": {v: \"1.0.0\"}, \"corp.example/geo\": {v: \"1.0.0\"}")
	pkgVendorTree(t, dir, "corp.example/s", map[string]string{
		"pkg.aontu": "pkg: {path: \"corp.example/s\"}\n" +
			"dep: {\"corp.example/geo\": {v: \"1.0.0\"}}\n",
		"main.aontu": pkgToolSource,
	})
	pkgVendorTree(t, dir, "corp.example/geo", map[string]string{
		"pkg.aontu":  "pkg: {path: \"corp.example/geo\"}\n",
		"main.aontu": "region: string\n",
	})
	if _, _, code := pkgRun("tidy", dir); 0 != code {
		t.Fatal("tidy")
	}

	out, _, code := pkgRun("tree", dir)
	want := "verdict: ok\ncorp.example/app\n  corp.example/geo 1.0.0\n" +
		"  corp.example/s 1.0.0\n    corp.example/geo 1.0.0 (above)\n"
	if 0 != code || want != out {
		t.Fatalf("tree = %d:\n%s", code, out)
	}
	if out, _, code := pkgRun("tree", "--format", "json", dir); 0 != code ||
		!strings.Contains(out, "\"root\": \"corp.example/app\"") {
		t.Fatalf("tree json = %d:\n%s", code, out)
	}

	same, _, code := pkgRun("refreeze", dir)
	if 0 != code || !strings.Contains(same, "corp.example/geo: unchanged") {
		t.Fatalf("refreeze = %d:\n%s", code, same)
	}
	lockPath := filepath.Join(dir, "aontu_meta", "pkg-lock.aontu")
	lock, _ := os.ReadFile(lockPath)
	stale := strings.Replace(string(lock), "\"canon\":\"aon1-", "\"canon\":\"aon1-stale", 1)
	pkgWrite(t, lockPath, stale)
	out, _, code = pkgRun("refreeze", dir)
	if 0 != code || !strings.Contains(out, ": aon1-stale") || !strings.Contains(out, " -> aon1-") {
		t.Fatalf("repin = %d:\n%s", code, out)
	}

	pkgWrite(t, lockPath, strings.Replace(string(lock), "}}}",
		"},\"corp.example/gone\":{\"archive\":\"\",\"canon\":\"aon1-g\",\"v\":\"1\"}}}", 1))
	pkgWrite(t, filepath.Join(dir, "pkg.aontu"),
		"dep: {\"corp.example/s\": {v: \"1.0.0\"}, \"corp.example/gone\": {v: \"1\"}, \"corp.example/never\": {v: \"1\"}}\n")
	if out, _, code := pkgRun("refreeze", dir); 1 != code ||
		!strings.Contains(out, "corp.example/gone: not fetched") {
		t.Fatalf("refreeze missing = %d:\n%s", code, out)
	}
	if out, _, code := pkgRun("tree", dir); 1 != code ||
		!strings.HasPrefix(out, "verdict: missing\n.\n") ||
		!strings.Contains(out, "  corp.example/gone 1\n") ||
		!strings.Contains(out, "corp.example/never (not locked)") {
		t.Fatalf("tree missing = %d:\n%s", code, out)
	}
	pkgWrite(t, lockPath, string(lock))
	pkgWrite(t, filepath.Join(dir, "aontu_meta", "vendor", "corp.example", "geo", "main.aontu"),
		"a: 1\na: 2\n")
	if out, _, code := pkgRun("refreeze", dir); 4 != code ||
		!strings.Contains(out, "does not evaluate on its own") {
		t.Fatalf("refreeze unevaluable = %d:\n%s", code, out)
	}
}

func TestPkgVendorRefusesAnEscapingPath(t *testing.T) {
	dir := pkgProject(t, "")
	v, _ := aontu.New().Unify(pkgToolSource)
	hash := aontu.CanonHash(v)

	// The package sits in the cache under its pin, so the ONLY thing
	// standing between the lockfile and the copy is the path gate.
	xdg := filepath.Join(dir, "xdg")
	cachedir := filepath.Join(xdg, "aontu", "pkg", "store", hash, "corp.example", "schemas", "service")
	pkgWrite(t, filepath.Join(cachedir, "pkg.aontu"), pkgServiceFiles["pkg.aontu"])
	pkgWrite(t, filepath.Join(cachedir, "service.aontu"), pkgToolSource)

	escaping := "corp.example/../../../outside/pwned"
	pkgWrite(t, filepath.Join(dir, "aontu_meta", "pkg-lock.aontu"),
		"{\"lock\":{\""+escaping+"\":{\"archive\":\"\",\"canon\":\""+hash+
			"\",\"v\":\"1.0.0\"}}}\n")

	t.Setenv("XDG_CACHE_HOME", xdg)
	out, _, code := pkgRun("vendor", dir)

	// Nothing outside the project, at any of the levels `..` reaches.
	for _, up := range []string{
		filepath.Join(dir, "..", "..", "outside"),
		filepath.Join(dir, "..", "outside"),
		filepath.Join(dir, "outside"),
	} {
		if _, err := os.Stat(up); nil == err {
			t.Fatalf("wrote outside the project: %s", up)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "aontu_meta", "vendor")); nil == err {
		t.Fatalf("want no vendor tree at all:\n%s", out)
	}
	if 1 != code || !strings.Contains(out, escaping+": not fetched") {
		t.Fatalf("want 1 (missing) naming the module, got %d:\n%s", code, out)
	}
}

// A project still carrying the older layout -- mod.aon, a root or
// aontu_meta/ mod-lock.aon, aon_vendor/ -- is told the current one,
// once, whatever the verb; nothing there is read (ADR-039).
func TestPkgNamesTheOldLayout(t *testing.T) {
	dir := t.TempDir()
	pkgWrite(t, filepath.Join(dir, "mod.aon"), "mod: { path: \"corp.example/app\" }\n")
	if err := os.MkdirAll(filepath.Join(dir, "aon_vendor"), 0o755); nil != err {
		t.Fatal(err)
	}
	var out, errw bytes.Buffer
	run([]string{"pkg", "verify", dir}, strings.NewReader(""), &out, &errw, false)
	if !strings.Contains(errw.String(), "aon_vendor, mod.aon belong to an older layout") ||
		!strings.Contains(errw.String(), "rename pkg.aontu's `mod` block to `pkg`") {
		t.Fatalf("no hint: %q", errw.String())
	}
	dir2 := t.TempDir()
	pkgWrite(t, filepath.Join(dir2, "pkg.aontu"), "pkg: { path: \"corp.example/app\" }\n")
	pkgWrite(t, filepath.Join(dir2, "mod-lock.aon"), "# mod-lock.aon\n{\"lock\":{}}\n")
	errw.Reset()
	run([]string{"pkg", "verify", dir2}, strings.NewReader(""), &out, &errw, false)
	if !strings.Contains(errw.String(), "older layout") {
		t.Fatalf("no hint for the lockfile: %q", errw.String())
	}
	dir3 := t.TempDir()
	pkgWrite(t, filepath.Join(dir3, "pkg.aontu"), "pkg: { path: \"corp.example/app\" }\n")
	errw.Reset()
	run([]string{"pkg", "verify", dir3}, strings.NewReader(""), &out, &errw, false)
	if strings.Contains(errw.String(), "older layout") {
		t.Fatalf("hint on the new layout: %q", errw.String())
	}
}

func TestModelDispatchesTheDocumentVerbs(t *testing.T) {
	var out, errw bytes.Buffer
	if code := run([]string{"model", "--help"}, strings.NewReader(""), &out, &errw, false); 0 != code ||
		!strings.Contains(out.String(), "Usage: aontu") {
		t.Fatalf("model --help = %d", code)
	}
	for _, args := range [][]string{{"model"}, {"model", "nope"}} {
		errw.Reset()
		if code := run(args, strings.NewReader(""), &out, &errw, false); 2 != code ||
			!strings.Contains(errw.String(), "model needs get, why or set") {
			t.Fatalf("%v = %d: %s", args, code, errw.String())
		}
	}
	dir := t.TempDir()
	file := filepath.Join(dir, "doc.aontu")
	pkgWrite(t, file, "a: 1\n")
	out.Reset()
	if code := run([]string{"model", "get", "$.a", file}, strings.NewReader(""), &out, &errw, false); 0 != code ||
		"1" != strings.TrimSpace(out.String()) {
		t.Fatalf("model get = %d: %s", code, out.String())
	}
	out.Reset()
	if code := run([]string{"model", "why", "$.a", file}, strings.NewReader(""), &out, &errw, false); 0 != code ||
		!strings.Contains(out.String(), "$.a = 1") {
		t.Fatalf("model why = %d: %s", code, out.String())
	}
	if code := run([]string{"model", "set", "$.b=2", "--dry-run", "--entry", file,
		"--overlay", filepath.Join(dir, "ov.aontu")}, strings.NewReader(""), &out, &errw, false); 0 != code {
		t.Fatalf("model set = %d", code)
	}
}
